export const portfolioData = {
  personal: {
    name: "Ismail ECHIKHI",
    title: "Développeur Fullstack Java/Angular · Tech Lead",
    phone: "07 58 55 00 65",
    email: "ismail.echikhi@gmail.com",
    linkedin: "https://www.linkedin.com/in/ismail-echikhi-12149b75/",
    malt: "https://www.malt.fr/profile/ismailechchikhi1?origin=dashboard_profile_name",
    collective: "https://app.collective.work/collective/ismail-ech/profile?tab=1",
    calendly: "https://calendly.com/ismail-echikhi",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/arnaud_fernandes-n8gtjVE9kiK6tfRJDInPvrdYLV2p9C.jpg",
},

  about: {
    bio: "Développeur fullstack Java/Angular avec 10 ans d'expérience sur des projets complexes pour grands comptes (EDF, BNP Paribas, Société Générale, Carrefour). Expertise en architecture microservices Spring Cloud, développement backend Java/JEE et frontend Angular/React, déploiement cloud AWS (EKS, CloudWatch, S3) et leadership technique (revues de code, standards sécurité, coordination Agile/Scrum). Fondateur de Meallan, plateforme SaaS de fidélité restauration.",
    summary:
      "Plus qu'un développeur. Un accélérateur. J'interviens là où la qualité et la fiabilité ne sont pas négociables.",
  },

  skills: {
    "Développement Fullstack": [
      "Java 21",
      "Java 17",
      "Java 8",
      "JavaScript",
      "TypeScript",
      "Spring Boot",
      "Spring MVC",
      "Spring Security",
      "Spring Data",
      "Spring Cloud",
      "Spring Batch",
      "Hibernate",
      "JPA",
      "NodeJS",
      "NestJS",
      "TypeORM",
      "Angular 5 → 12+",
      "React 16+",
      "React Native",
      "AngularJS",
      "RxJS",
      "Angular Material",
      "Bootstrap",
      "PrimeNG",
      "MapStruct",
      "Bean Validation",
    ],
    "Architecture & Cloud": [
      "Architecture microservices",
      "Spring Cloud",
      "AWS EKS",
      "Amazon CloudWatch",
      "Amazon S3",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Git / Git Flow / GitLab / GitHub",
      "Maven",
      "Sonar",
      "Event-Driven (Kafka, RabbitMQ, IBM MQ)",
      "API REST / SOAP / GraphQL",
      "Swagger",
      "Camunda (BPMN)",
      "Airflow",
      "Apache Camel",
      "Ansible",
    ],
    "Bases de données": [
      "PostgreSQL",
      "MySQL",
      "Oracle / PL-SQL",
      "MongoDB",
      "Couchbase",
      "Liquibase",
    ],
    "Tests & Qualité": [
      "JUnit",
      "Mockito",
      "Jasmine",
      "Jest",
      "Cucumber",
      "TDD",
      "BDD",
    ],
    "Autres": [
      "Domain-Driven Design (DDD)",
      "Stripe (abonnements, essais, paiements récurrents)",
      "Sécurité : JWT, SSL/TLS, Spring Security",
      "Scrum / Kanban (Jira, Confluence)",
    ],
  },

  experience: [
    {
      company: "EDF",
      position: "Tech Lead · Conception et Développement Web",
      period: "Juillet 2023 — Présent",
      location: "France",
      description:
        "Pilotage technique et développement sur la gestion des chantiers nucléaires. Architecture microservices avec Spring Cloud orchestrée via Amazon EKS.",
      highlights: [
        "Équipe Transverse (C90) – Développement d'une librairie de supervision intégrant métriques et logs CloudWatch pour monitoring centralisé des microservices. Pilotage technique, garant qualité via revues de code et respect des standards sécurité/conformité.",
        "Module Gestion Santé et Sécurité (GSS) – Outils de suivi de conformité sécurité avec stockage sécurisé des documents et rapports sur Amazon S3.",
        "Module PPSPS – Automatisation des processus métiers avec persistance documentaire S3 et logs d'activité monitorés via CloudWatch.",
        "Modules Déblais / Référentiel / Parcelles – Suivi des matériaux issus des travaux, gestion centralisée des données de référence, coordination logistique des chantiers.",
        "Module Gouvernance – Système centralisé de gestion des droits et accès.",
        "Module Produits chimiques – Gestion des substances dangereuses et non-dangereuses pour conformité réglementaire. Publication et consommation des messages via Kafka pour architecture event-driven.",
      ],
      technologies: [
        "Java 17",
        "Maven",
        "Spring Framework",
        "Spring Cloud",
        "Kafka",
        "JPA",
        "Hibernate",
        "Jenkins",
        "GitLab",
        "REST",
        "Oracle",
        "Camunda",
        "AWS (EKS, CloudWatch, S3)",
        "Angular",
      ],
    },
    {
      company: "Meallan (www.meallan.net)",
      position: "Fondateur & Développeur Fullstack",
      period: "2023 — Présent",
      location: "Web",
      description:
        "Création et lancement de Meallan, plateforme digitale innovante de fidélité pour restaurants. Gestion du projet de bout en bout : conception, développement, hébergement, sécurité et mise en production.",
      highlights: [
        "Plateforme SaaS de fidélité restaurants – Conception de l'architecture complète et développement fullstack : NestJS (backend), Angular (portail web), React Native (applications mobiles iOS/Android).",
        "Système de points cumulables et échangeables dans tout le réseau de restaurants partenaires.",
        "API GraphQL optimisée pour la communication inter-applications.",
        "Intégration des paiements récurrents Stripe : abonnements restaurants, essais gratuits, gestion des paiements.",
        "Déploiement et publication des applications sur Google Play et App Store.",
      ],
      technologies: [
        "NodeJS (NestJS)",
        "TypeORM",
        "GraphQL",
        "Angular",
        "MySQL",
        "React Native",
        "Stripe",
        "Google Play",
        "App Store",
      ],
    },
    {
      company: "BNP Paribas",
      position: "Ingénieur d'Études & Développement Java/JEE · Angular",
      period: "Octobre 2021 — Juin 2023",
      location: "France",
      description:
        "Projets FININSIGHT (pilotage et supervision messagerie bancaire) et Injecteur des messages SIBES.",
      highlights: [
        "Projet FININSIGHT – Application de pilotage et supervision de la messagerie bancaire : APIs REST, authentification JWT, gestion des habilitations. Intégration de l'outil DIMS pour contrôle d'intégrité des données. Génération des rapports hebdomadaires des nacks SIBES par Spring Batch. Monitoring des flux avec gestion des alertes en temps réel. Tests unitaires JUnit/Mockito.",
        "Projet Injecteur de messages – Application de publication des messages SIBES dans des queues (IBM MQ) consommées par les applications aval. IHM Angular 12, modélisation BDD avec DDD, gestion utilisateurs/profils/droits, Git Flow.",
      ],
      technologies: [
        "Angular 12",
        "Java 17",
        "Spring Framework",
        "Spring Batch",
        "REST",
        "JWT",
        "Oracle",
        "Mockito",
        "Docker",
        "IBM MQ",
        "DDD",
        "Git Flow",
      ],
    },
    {
      company: "Société Générale",
      position: "Ingénieur d'Études & Développement Java/JEE · React",
      period: "Mars 2019 — Septembre 2021",
      location: "France",
      description:
        "Projets ALM GARLIQ (gestion actif-passif) et MARKET DATA (collecte données financières Bloomberg).",
      highlights: [
        "Projet ALM GARLIQ – Système de gestion actif-passif interfacé avec le progiciel FusionRisk de Finastra : orchestration des opérations en workflow (Airflow). APIs REST documentées sur Swagger. Authentification JWT. Mapping MapStruct. Déploiements automatisés via playbooks Ansible. Versioning BDD avec Liquibase. IHM React 16. Mise en place du TDD.",
        "Projet MARKET DATA – Collecte de l'ensemble des données financières du marché fournies par Bloomberg pour la construction de courbes. Fiabilisation du code par TDD.",
      ],
      technologies: [
        "React 16",
        "Java 8",
        "Ansible",
        "Spring Framework",
        "REST",
        "JWT",
        "Oracle",
        "Mockito",
        "TDD",
        "Liquibase",
        "Airflow",
        "Swagger",
        "MapStruct",
        "FusionRisk",
        "Bloomberg",
      ],
    },
    {
      company: "Carrefour",
      position: "Ingénieur d'Études & Développement Java/JEE · Angular",
      period: "Février 2018 — Mars 2019",
      location: "France",
      description:
        "Projets Middleware fidélité (gestion cartes fidélité) et OMS (gestion commandes CLCV, Drive, Marketplace).",
      highlights: [
        "Projet Middleware Fidélité – Middleware de gestion des cartes fidélité Carrefour, intermédiaire entre front web/mobile et back-ends Siebel/Stac. APIs REST (swagger-codegen-maven-plugin). Optimisation via cache NoSQL Couchbase. Routage SOAP avec Apache Camel (cxf-codegen-plugin). IHM Angular 5. Authentification JWT. Batch Spring Batch (CSV → BDD). Publication Kafka. Tests JUnit/Mockito/Cucumber (BDD).",
        "Projet OMS – Gestion des commandes Carrefour (CLCV, Drive, Marketplace) via un workflow multi-process : microservices communicant via RabbitMQ, orchestration BPMN2 avec Camunda, Web Services SOAP Spring, BDD avec Cucumber.",
      ],
      technologies: [
        "Angular 5",
        "Java 8",
        "Spring Framework",
        "Spring Batch",
        "REST",
        "SOAP",
        "JWT",
        "Oracle",
        "Kafka",
        "RabbitMQ",
        "Couchbase",
        "Apache Camel",
        "Camunda",
        "Cucumber",
        "JUnit",
        "Mockito",
      ],
    },
    {
      company: "FY Computing",
      position: "Ingénieur d'Études & Développement Java/JEE · Angular",
      period: "Septembre 2015 — Janvier 2018",
      location: "France",
      description:
        "Réalisation d'applications Spring Boot pour la gestion de bus (Sénégal), assurances (Transvie), e-commerce formations (STIHL) et portail immobilier. Rôle de chef de projet sur les projets ITICKET et IMute.",
      highlights: [
        "Projet ITICKET (Chef de projet) – Application Spring Boot de gestion des bus au Sénégal : gestion du personnel, des autobus, des lignes et des trajets. Application mobile Android Studio (authentification, démarrage trajet, feuille de route). Bilan mensuel de production. Animation du Daily Scrum.",
        "Projet IMute (Chef de projet) – Application Spring Boot de gestion des assurances Transvie (adhérents, agences, recouvrement, prestations). Développement partiel en Ruby on Rails 4.2.",
        "Projet ORCHESTRA – Plateforme e-commerce de gestion de formations : catalogues, profils, rôles (Spring Security), panier AngularJS avec paiement. Synchronisation SOAP avec backoffice STIHL via jaxWs. Injection des dépendances Spring IOC.",
        "Projet ALYSTAIR – Portail immobilier Spring Boot : gestion des utilisateurs/droits, annonces (location/vente), module de recherche multi-critères, REST avec AngularJS, ORM Hibernate/JPA.",
      ],
      technologies: [
        "Java 8",
        "Spring Boot",
        "Spring Security",
        "Spring Data",
        "Spring IOC",
        "Spring MVC REST",
        "AngularJS",
        "NodeJS",
        "Ruby on Rails 4.2",
        "Android Studio",
        "JPA",
        "Hibernate",
        "MySQL",
        "Oracle",
        "SOAP",
        "javaxWs",
        "Git",
        "Maven",
        "REST",
        "JWT",
        "Mockito",
        "TDD",
      ],
    },
  ],

  education: [
    {
      school: "Université de Nice Sophia Antipolis",
      degree: "Master MIAGE",
      year: "2015",
      location: "Nice, France",
    },
    {
      school: "École Marocaine des Sciences de l'Ingénieur (EMSI)",
      degree: "Diplôme d'Ingénieur",
      year: "2015",
      location: "Maroc",
    },
  ],

  languages: [
    { language: "Français", level: "Bilingue" },
    { language: "Anglais", level: "Professionnel" },
  ],

  colors: {
    primary: "#0052CC",   // Bleu profond (confiance, tech)
    secondary: "#00D4FF", // Cyan électrique (modernité)
    accent: "#00C853",    // Vert validation (qualité)
    background: "#FFFFFF",
    foreground: "#1A1A1A",
    border: "#E5E5E5",
    muted: "#7A7A7A",
  },
};